import { Image } from 'expo-image';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import Animated, { FadeIn } from 'react-native-reanimated';
import { Screen } from '@/components/common/screen';
import { AppText, BackButton, Brand, Card, FormInput, PrimaryButton, SecondaryButton } from '@/components/common/ui';
import { assets, colors } from '@/constants/theme';

export function SplashScreen() {
  useEffect(() => { const id = setTimeout(() => router.replace('/onboarding'), 1800); return () => clearTimeout(id); }, []);
  return <Screen scroll={false} variant={4}><Animated.View entering={FadeIn.duration(500)} style={s.splash}><Brand /><AppText variant="hero" style={s.center}>Smarter habits.{`\n`}<AppText variant="hero" style={{ color: colors.success }}>Brighter tomorrows.</AppText></AppText><AppText style={[s.center, s.muted]}>Take control of your spending{`\n`}one receipt at a time.</AppText><Image source={assets.mascotNeutral} contentFit="contain" style={s.splashMascot} /><View style={s.dots}><View style={s.dotActive}/><View style={s.dot}/><View style={s.dot}/></View><AppText style={{ color: colors.forest }}>Loading your brighter tomorrow...</AppText></Animated.View></Screen>;
}
export function OnboardingScreen() { return <Screen variant={3}><View style={s.onboarding}><Brand compact /><Image source={assets.mascotNeutral} contentFit="contain" style={s.onboardMascot}/><AppText variant="title" style={s.center}>Track smarter,{`\n`}not harder.</AppText><AppText style={[s.center,s.muted]}>Turn receipts into verified expense records{`\n`}and understand your spending with less effort.</AppText>{[['▤','Scan Receipts','Snap a photo, we do the rest.'],['✓','Verify Details','We extract and confirm the key info.'],['▥','See Insights','Understand your spending, grow smarter.']].map(x=><Card key={x[1]} style={s.feature}><View style={s.featureIcon}><AppText variant="h2">{x[0]}</AppText></View><View><AppText variant="h3">{x[1]}</AppText><AppText variant="small" style={s.muted}>{x[2]}</AppText></View></Card>)}<View style={s.dots}><View style={s.dotActive}/><View style={s.dot}/><View style={s.dot}/></View><PrimaryButton title="Get Started" onPress={()=>router.push('/welcome')}/><Pressable onPress={()=>router.replace('/welcome')}><AppText style={[s.center,s.muted]}>Skip for now</AppText></Pressable></View></Screen>; }

export function WelcomeScreen() { return <Screen variant={4}><View style={s.welcome}><Brand /><AppText variant="hero">Smarter receipt{`\n`}tracking, built{`\n`}around verified{`\n`}data.</AppText><AppText style={s.muted}>Scan receipts, review extracted details, and turn verified transactions into useful spending insights.</AppText><Image source={assets.mascotNeutral} contentFit="contain" style={s.welcomeMascot}/><Card style={s.welcomeCard}><Image source={assets.logoMark} style={{width:64,height:64}}/><View style={{flex:1}}><AppText variant="h3">Scan. Verify. Understand.</AppText><AppText style={s.muted}>Turn your receipts into verified transactions and clear insights.</AppText></View></Card><PrimaryButton title="Get Started" onPress={()=>router.push('/create-account')}/><SecondaryButton title="I already have an account" onPress={()=>router.push('/sign-in')}/></View></Screen>; }

function AuthShell({ back=false, children }: { back?: boolean; children: React.ReactNode }) { return <Screen variant={4}><View style={s.auth}>{back && <BackButton/>}<Brand compact />{children}</View></Screen>; }
function PasswordEye({ visible, toggle }: { visible:boolean; toggle:()=>void }) { return <Pressable onPress={toggle} hitSlop={10}><AppText variant="h3">{visible?'◉':'◎'}</AppText></Pressable>; }
export function SignInScreen() { const [show,setShow]=useState(false); return <AuthShell><AppText variant="hero">Welcome back</AppText><AppText style={s.muted}>Sign in to continue to ExpenSense.</AppText><View style={s.form}><FormInput icon="✉" placeholder="Email" keyboardType="email-address" autoCapitalize="none"/><FormInput icon="▣" placeholder="Password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><Pressable onPress={()=>router.push('/forgot-password')}><AppText style={s.link}>Forgot password?</AppText></Pressable><PrimaryButton title="Sign In" onPress={()=>router.replace('/home')}/><Pressable onPress={()=>router.push('/create-account')}><AppText style={s.center}>New to ExpenSense? <AppText variant="h3" style={{color:colors.deepForest}}>Create account</AppText></AppText></Pressable></View></AuthShell>; }
export function ForgotPasswordScreen() { return <AuthShell back><AppText variant="hero">Forgot{`\n`}password?</AppText><AppText style={s.muted}>Enter your email and we’ll send a reset link.</AppText><View style={s.form}><FormInput icon="✉" placeholder="Email address" keyboardType="email-address"/><PrimaryButton title="Send Reset Link" onPress={()=>router.push('/create-new-password')}/><Pressable onPress={()=>router.replace('/sign-in')}><AppText variant="h3" style={s.center}>Back to sign in</AppText></Pressable></View></AuthShell>; }
export function CreateNewPasswordScreen() { const [show,setShow]=useState(false); return <AuthShell back><AppText variant="hero">Create a new{`\n`}password</AppText><AppText style={s.muted}>Use a strong password to secure your account.</AppText><View style={s.form}><FormInput icon="▣" placeholder="New password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><FormInput icon="▣" placeholder="Confirm password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><PrimaryButton title="Update Password" onPress={()=>router.replace('/sign-in')}/></View></AuthShell>; }
export function CreateAccountScreen() { const [show,setShow]=useState(false); return <AuthShell back><AppText variant="hero">Create your{`\n`}account</AppText><AppText style={s.muted}>Start tracking verified expenses.</AppText><View style={s.formCompact}><FormInput icon="♙" placeholder="Full name"/><FormInput icon="✉" placeholder="Email" keyboardType="email-address"/><FormInput icon="▣" placeholder="Password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><FormInput icon="▣" placeholder="Confirm password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><PrimaryButton title="Create Account" onPress={()=>router.replace('/home')}/><Pressable onPress={()=>router.replace('/sign-in')}><AppText style={s.center}>Already have an account? <AppText variant="h3">Sign in</AppText></AppText></Pressable></View></AuthShell>; }
const s=StyleSheet.create({
  splash:{flex:1,alignItems:'center',justifyContent:'center',padding:28,gap:22},center:{textAlign:'center'},muted:{color:colors.muted},splashMascot:{width:280,height:240},dots:{flexDirection:'row',gap:10,justifyContent:'center',alignItems:'center'},dot:{width:10,height:10,borderRadius:5,backgroundColor:'#C8D8C1'},dotActive:{width:10,height:10,borderRadius:5,backgroundColor:colors.deepForest},
  onboarding:{paddingHorizontal:30,paddingBottom:20,alignItems:'stretch',gap:10},onboardMascot:{width:'100%',height:175,marginTop:-24},feature:{flexDirection:'row',alignItems:'center',padding:9,gap:14,backgroundColor:'rgba(232,238,227,.94)'},featureIcon:{width:58,height:44,borderRadius:14,backgroundColor:'#D6E3CC',alignItems:'center',justifyContent:'center'},
  welcome:{padding:28,gap:16},welcomeMascot:{width:190,height:160,alignSelf:'flex-end',marginTop:-55},welcomeCard:{flexDirection:'row',alignItems:'center',gap:16},auth:{padding:29,gap:20,justifyContent:'center',flex:1,minHeight:650},form:{gap:14,marginTop:20},formCompact:{gap:10,marginTop:8},link:{textAlign:'right',color:colors.deepForest,fontFamily:'JakartaMedium'},
});
