import { Image } from 'expo-image';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native';
import Animated, { FadeIn } from 'react-native-reanimated';
import { Screen } from '@/components/common/screen';
import { LiquidScene } from '@/components/common/liquid-scene';
import { AppIcon, AppText, BackButton, Brand, Card, FormInput, PrimaryButton, SecondaryButton } from '@/components/common/ui';
import { assets, colors } from '@/constants/theme';

export function SplashScreen() {
  const { height } = useWindowDimensions();
  useEffect(() => { const id = setTimeout(() => router.push('/onboarding'), 2200); return () => clearTimeout(id); }, []);
  return <Screen scroll={false} background={false}><LiquidScene scene="splash"/><Animated.View entering={FadeIn.duration(650)} style={[s.splash,{minHeight:height}]}><View style={s.splashCopy}><Brand /><AppText variant="hero" style={s.center}>Smarter habits.{`\n`}<AppText variant="hero" style={s.green}>Brighter tomorrows.</AppText></AppText><AppText variant="h3" style={[s.center,s.muted]}>Take control of your spending{`\n`}one receipt at a time.</AppText></View><View style={s.splashLoading}><View style={s.dots}><View style={s.dotActive}/><View style={s.dot}/><View style={s.dot}/></View><AppText variant="bodyMedium" style={s.green}>Loading your brighter tomorrow...</AppText></View></Animated.View></Screen>;
}
export function OnboardingScreen() { const {height}=useWindowDimensions(); return <Screen background={false}><View style={[s.onboarding,{minHeight:Math.max(height,760)}]}><LiquidScene scene="onboarding"/><View style={s.backFloat}><BackButton/></View><View style={s.onboardBrand}><Brand compact /></View><View style={s.onboardContent}><AppText variant="title" style={s.center}>Track smarter,{`\n`}not harder.</AppText><AppText style={[s.center,s.muted]}>Turn receipts into verified expense records{`\n`}and understand your spending with less effort.</AppText>{([['receipt-text-outline','Scan Receipts','Snap a photo, we do the rest.'],['shield-check','Verify Details','We extract and confirm the key info.'],['chart-bar','See Insights','Understand your spending, grow smarter.']] as const).map(x=><Card key={x[1]} style={s.feature}><View style={s.featureIcon}><AppIcon name={x[0]} size={28}/></View><View style={{flex:1}}><AppText variant="h3">{x[1]}</AppText><AppText variant="small" style={s.muted}>{x[2]}</AppText></View></Card>)}<View style={s.dots}><View style={s.dotActive}/><View style={s.dot}/><View style={s.dot}/></View><PrimaryButton title="Get Started" onPress={()=>router.push('/welcome')}/><Pressable onPress={()=>router.push('/welcome')}><AppText variant="bodyMedium" style={[s.center,s.muted]}>Skip for now</AppText></Pressable></View></View></Screen>; }

export function WelcomeScreen() { const {height}=useWindowDimensions(); return <Screen background={false}><View style={[s.welcome,{minHeight:Math.max(height,780)}]}><LiquidScene scene="welcome"/><View style={s.backFloat}><BackButton/></View><View style={s.welcomeBrand}><Brand /></View><View style={s.welcomeCopy}><AppText variant="hero">Smarter receipt{`\n`}tracking, built{`\n`}around verified{`\n`}data.</AppText><AppText variant="h3" style={s.muted}>Scan receipts, review extracted{`\n`}details, and turn verified{`\n`}transactions into useful{`\n`}spending insights.</AppText></View><View style={s.welcomeActions}><Card style={s.welcomeCard}><View style={s.logoBubble}><Image source={assets.logoMark} contentFit="contain" style={s.logoBubbleImage}/></View><View style={{flex:1}}><AppText variant="h3">Scan. Verify. Understand.</AppText><AppText style={s.muted}>Turn your receipts into verified transactions and clear insights.</AppText></View></Card><View style={s.welcomeDots}><View style={s.dotActive}/><View style={s.dot}/><View style={s.dot}/><View style={s.dot}/></View><PrimaryButton title="Get Started" onPress={()=>router.push('/create-account')}/><SecondaryButton title="I already have an account" onPress={()=>router.push('/sign-in')}/></View></View></Screen>; }

function AuthShell({ back=false, children }: { back?: boolean; children: React.ReactNode }) { return <Screen variant={4}><View style={s.auth}>{back && <BackButton/>}<Brand compact />{children}</View></Screen>; }
function PasswordEye({ visible, toggle }: { visible:boolean; toggle:()=>void }) { return <Pressable onPress={toggle} hitSlop={10}><AppIcon name={visible?'eye-off-outline':'eye-outline'} size={22}/></Pressable>; }
export function SignInScreen() { const [show,setShow]=useState(false); return <AuthShell><AppText variant="hero">Welcome back</AppText><AppText style={s.muted}>Sign in to continue to ExpenSense.</AppText><View style={s.form}><FormInput icon="email-outline" placeholder="Email" keyboardType="email-address" autoCapitalize="none"/><FormInput icon="lock-outline" placeholder="Password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><Pressable onPress={()=>router.push('/forgot-password')}><AppText style={s.link}>Forgot password?</AppText></Pressable><PrimaryButton title="Sign In" onPress={()=>router.replace('/home')}/><Pressable onPress={()=>router.push('/create-account')}><AppText style={s.center}>New to ExpenSense? <AppText variant="h3" style={{color:colors.deepForest}}>Create account</AppText></AppText></Pressable></View></AuthShell>; }
export function ForgotPasswordScreen() { return <AuthShell back><AppText variant="hero">Forgot{`\n`}password?</AppText><AppText style={s.muted}>Enter your email and we’ll send a reset link.</AppText><View style={s.form}><FormInput icon="email-outline" placeholder="Email address" keyboardType="email-address"/><PrimaryButton title="Send Reset Link" onPress={()=>router.push('/create-new-password')}/><Pressable onPress={()=>router.replace('/sign-in')}><AppText variant="h3" style={s.center}>Back to sign in</AppText></Pressable></View></AuthShell>; }
export function CreateNewPasswordScreen() { const [show,setShow]=useState(false); return <AuthShell back><AppText variant="hero">Create a new{`\n`}password</AppText><AppText style={s.muted}>Use a strong password to secure your account.</AppText><View style={s.form}><FormInput icon="lock-outline" placeholder="New password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><FormInput icon="lock-outline" placeholder="Confirm password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><PrimaryButton title="Update Password" onPress={()=>router.replace('/sign-in')}/></View></AuthShell>; }
export function CreateAccountScreen() { const [show,setShow]=useState(false); return <AuthShell back><AppText variant="hero">Create your{`\n`}account</AppText><AppText style={s.muted}>Start tracking verified expenses.</AppText><View style={s.formCompact}><FormInput icon="account-outline" placeholder="Full name"/><FormInput icon="email-outline" placeholder="Email" keyboardType="email-address"/><FormInput icon="lock-outline" placeholder="Password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><FormInput icon="lock-outline" placeholder="Confirm password" secure={!show} right={<PasswordEye visible={show} toggle={()=>setShow(!show)}/>} /><PrimaryButton title="Create Account" onPress={()=>router.replace('/home')}/><Pressable onPress={()=>router.replace('/sign-in')}><AppText style={s.center}>Already have an account? <AppText variant="h3">Sign in</AppText></AppText></Pressable></View></AuthShell>; }
const s=StyleSheet.create({
  center:{textAlign:'center'},muted:{color:colors.muted},green:{color:colors.forest},
  splash:{flex:1,alignItems:'center',paddingHorizontal:24},splashCopy:{position:'absolute',top:'14%',alignItems:'center',gap:24},splashLoading:{position:'absolute',top:'80%',alignItems:'center',gap:16},
  dots:{flexDirection:'row',gap:10,justifyContent:'center',alignItems:'center'},dot:{width:10,height:10,borderRadius:5,backgroundColor:'#C8D8C1'},dotActive:{width:10,height:10,borderRadius:5,backgroundColor:colors.deepForest},
  backFloat:{position:'absolute',left:18,top:16,zIndex:20},
  onboarding:{paddingHorizontal:24,paddingBottom:22},onboardBrand:{position:'absolute',top:32,left:0,right:0,alignItems:'center'},onboardContent:{paddingTop:330,gap:10},feature:{flexDirection:'row',alignItems:'center',paddingVertical:10,paddingHorizontal:12,gap:14,backgroundColor:'rgba(238,242,233,.96)',borderRadius:22},featureIcon:{width:58,height:48,borderRadius:17,backgroundColor:'#DCE8D5',alignItems:'center',justifyContent:'center'},
  welcome:{paddingHorizontal:25,paddingBottom:26},welcomeBrand:{position:'absolute',top:42,left:24},welcomeCopy:{paddingTop:150,gap:18},welcomeActions:{marginTop:110,gap:12},welcomeCard:{flexDirection:'row',alignItems:'center',gap:14,padding:14,borderRadius:22},logoBubble:{width:76,height:76,borderRadius:38,backgroundColor:'#E4EDDD',alignItems:'center',justifyContent:'center'},logoBubbleImage:{width:58,height:58},welcomeDots:{flexDirection:'row',gap:9,justifyContent:'center',paddingVertical:3},
  auth:{padding:29,gap:20,justifyContent:'center',flex:1,minHeight:650},form:{gap:14,marginTop:20},formCompact:{gap:10,marginTop:8},link:{textAlign:'right',color:colors.deepForest,fontFamily:'JakartaMedium'},
});
