import { Image } from 'expo-image';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import Animated, { FadeIn, FadeInDown } from 'react-native-reanimated';
import { Screen } from '@/components/common/screen';
import { AppIcon, AppText, BackButton, Card, FormInput, PrimaryButton, SecondaryButton, StatusChip } from '@/components/common/ui';
import { assets, colors, radii } from '@/constants/theme';

export function AddExpenseScreen(){return <Screen variant={4}><View style={s.dim}/><View style={s.sheet}><View style={s.handle}/><View style={s.rowBetween}><AppText variant="title">Add Expense</AppText><Pressable onPress={()=>router.back()} style={s.close}><AppText variant="h2">×</AppText></Pressable></View>{[['⌗','Scan Receipt','Use your camera','/scanner'],['▧','Upload Receipt','Choose from gallery','/processing'],['▤','Manual Entry','Enter details manually','/manual-expense']].map(x=><Pressable key={x[1]} onPress={()=>router.push(x[3] as never)}><Card style={s.option}><View style={s.optionIcon}><AppText variant="h2" style={{color:colors.surface}}>{x[0]}</AppText></View><View style={{flex:1}}><AppText variant="h3">{x[1]}</AppText><AppText style={s.muted}>{x[2]}</AppText></View><AppText variant="title" style={s.muted}>›</AppText></Card></Pressable>)}</View></Screen>}
export function ScannerScreen(){return <Screen scroll={false} variant={4}><View style={s.scannerPage}><View style={s.camera}><View style={s.cameraTop}><Pressable onPress={()=>router.back()}><AppText variant="title" style={s.white}>×</AppText></Pressable><AppText variant="title" style={s.white}>ϟ</AppText></View><Image source={assets.receipt} contentFit="contain" style={s.scanReceipt}/><Image source={assets.scanFrame} contentFit="contain" style={s.scanFrame}/><View style={s.cameraBottom}><AppText style={s.white}>Position the receipt inside the frame.</AppText><View style={s.captureRow}><AppText variant="title" style={s.white}>▧</AppText><Pressable accessibilityLabel="Capture receipt" onPress={()=>router.replace('/processing')} style={s.capture}/><View style={{width:34}}/></View></View></View></View></Screen>}
export function ProcessingScreen(){const [done,setDone]=useState(0);useEffect(()=>{const id=setInterval(()=>setDone(v=>{if(v>=5){clearInterval(id);setTimeout(()=>router.replace('/receipt-review'),450);return v}return v+1}),550);return()=>clearInterval(id)},[]);const steps=['Checking image quality','Validating receipt','Extracting information','Checking totals','Preparing verification'];return <Screen scroll={false} variant={4}><View style={s.processing}><Animated.Image entering={FadeIn.duration(350)} source={assets.mascotSuccess} resizeMode="contain" style={s.processMascot}/><AppText variant="title">Reading receipt...</AppText><View style={s.steps}>{steps.map((x,i)=><Animated.View entering={FadeInDown.delay(i*80)} key={x} style={s.step}><View style={[s.stepCircle,i<done&&s.stepDone]}><AppText variant="h3" style={i<done?s.white:s.muted}>{i<done?'✓':''}</AppText></View><AppText variant="h3" style={i<done?undefined:s.muted}>{x}</AppText></Animated.View>)}</View></View></Screen>}
export function ReceiptReviewScreen(){return <Screen variant={4}><View style={s.page}><Card style={{gap:14}}><View style={s.reviewTop}><View style={s.receiptPhoto}><Image source={assets.receipt} contentFit="contain" style={{width:'100%',height:'100%'}}/></View><View style={{flex:1,gap:8}}><AppText variant="h2">Coffee Project</AppText><AppText style={s.muted}>Sep 14, 2024</AppText><StatusChip warning>Needs Review</StatusChip><AppText style={{color:colors.deepForest}}>87% confidence</AppText></View></View><View style={s.divider}/><AppText variant="h2">Items (3)</AppText><View style={s.box}>{[['Iced Latte','1','₱160'],['Blueberry Muffin','1','₱120'],['Bottled Water','1','₱50']].map(x=><View style={s.item} key={x[0]}><AppText style={{flex:1}}>{x[0]}</AppText><AppText>{x[1]}</AppText><AppText style={{width:80,textAlign:'right'}}>{x[2]}</AppText></View>)}</View><View style={s.box}><Info label="Subtotal" value="₱330"/><Info label="Tax" value="₱42"/><View style={s.divider}/><Info label="Total" value="₱392" bold/></View><FormInput icon="food-fork-drink" value="Food & Dining" editable={false}/><FormInput placeholder="Notes (optional)"/><PrimaryButton title="Confirm & Save" onPress={()=>router.replace('/transactions')}/></Card></View></Screen>}
function Info({label,value,bold=false}:{label:string;value:string;bold?:boolean}){return <View style={s.rowBetween}><AppText variant={bold?'h2':'body'}>{label}</AppText><AppText variant={bold?'h2':'body'}>{value}</AppText></View>}
export function RecognitionFailedScreen(){return <Screen scroll={false} variant={6}><View style={s.failed}><Image source={assets.mascotConfused} contentFit="contain" style={{width:260,height:240}}/><AppText variant="title" style={s.center}>We couldn’t recognize{`\n`}this as a receipt.</AppText><AppText style={[s.center,s.muted]}>Try a clearer photo or enter the{`\n`}details manually.</AppText><PrimaryButton title="Retake Photo" icon="camera-outline" onPress={()=>router.replace('/scanner')}/><SecondaryButton title="Upload Another Image" icon="upload-outline" onPress={()=>router.replace('/processing')}/><SecondaryButton title="Enter Manually" icon="pencil-outline" onPress={()=>router.replace('/manual-expense')}/></View></Screen>}
export function ManualExpenseScreen(){return <Screen variant={4}><View style={s.page}><BackButton/><AppText variant="title">Add Expense</AppText><Label text="Amount"/><FormInput icon="currency-php" placeholder="0.00" keyboardType="decimal-pad"/><Label text="Merchant / Description"/><FormInput placeholder="Enter merchant or description"/><Label text="Date"/><FormInput value="Sep 14, 2024" editable={false} right={<AppIcon name="calendar-outline"/>}/><Label text="Category"/><FormInput placeholder="Select category" right={<AppIcon name="chevron-down"/>}/><Label text="Notes (optional)"/><FormInput placeholder="Add a note (optional)" multiline style={{height:78}}/><Label text="Attach Receipt (optional)"/><Pressable style={s.attach}><AppIcon name="paperclip" size={28}/><AppText style={s.muted}>Tap to attach a receipt</AppText></Pressable><PrimaryButton title="Save Expense" onPress={()=>router.replace('/transactions')}/></View></Screen>}
function Label({text}:{text:string}){return <AppText variant="bodyMedium" style={{marginBottom:-10}}>{text}</AppText>}
const s=StyleSheet.create({page:{padding:26,gap:16},muted:{color:colors.muted},white:{color:colors.surface},center:{textAlign:'center'},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},dim:{...StyleSheet.absoluteFill,backgroundColor:colors.overlay},sheet:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:colors.surface,borderTopLeftRadius:32,borderTopRightRadius:32,padding:20,gap:12},handle:{width:44,height:5,borderRadius:3,backgroundColor:'#B8B6AF',alignSelf:'center'},close:{width:44,height:44,borderRadius:22,backgroundColor:colors.pale,alignItems:'center',justifyContent:'center'},option:{flexDirection:'row',alignItems:'center',gap:14},optionIcon:{width:56,height:56,borderRadius:16,backgroundColor:colors.forest,alignItems:'center',justifyContent:'center'},scannerPage:{flex:1,padding:24,justifyContent:'center'},camera:{height:'86%',borderRadius:24,overflow:'hidden',backgroundColor:'#1D271F',borderWidth:4,borderColor:'#DCE7D8'},cameraTop:{height:70,flexDirection:'row',justifyContent:'space-between',padding:20,zIndex:3},scanReceipt:{position:'absolute',width:'58%',height:'60%',top:'16%',left:'21%',transform:[{rotate:'-4deg'}]},scanFrame:{position:'absolute',width:'72%',height:'58%',top:'17%',left:'14%',tintColor:'#3CE8B0'},cameraBottom:{position:'absolute',left:0,right:0,bottom:0,height:170,backgroundColor:'rgba(0,0,0,.64)',alignItems:'center',justifyContent:'space-around',padding:18},captureRow:{width:'100%',flexDirection:'row',alignItems:'center',justifyContent:'space-around'},capture:{width:72,height:72,borderRadius:36,backgroundColor:colors.surface,borderWidth:5,borderColor:'white',outlineWidth:2,outlineColor:colors.surface},processing:{flex:1,alignItems:'center',justifyContent:'center',gap:24,padding:30},processMascot:{width:250,height:220},steps:{gap:16},step:{flexDirection:'row',alignItems:'center',gap:16},stepCircle:{width:34,height:34,borderRadius:17,borderWidth:2,borderColor:'#B7C0BD',alignItems:'center',justifyContent:'center'},stepDone:{backgroundColor:colors.success,borderColor:colors.success},reviewTop:{flexDirection:'row',gap:16},receiptPhoto:{width:'42%',height:210,borderRadius:14,backgroundColor:'#59442E',padding:8},divider:{height:1,backgroundColor:colors.line},box:{borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12,gap:8},item:{flexDirection:'row',gap:10,paddingVertical:6,borderBottomWidth:1,borderBottomColor:colors.line},failed:{flex:1,justifyContent:'center',padding:28,gap:18},attach:{height:100,borderWidth:1.5,borderStyle:'dashed',borderColor:colors.lightGreen,borderRadius:radii.md,alignItems:'center',justifyContent:'center',gap:6}});
