import { useMemo, useState } from 'react';
import { Alert, Keyboard, StyleSheet, View } from 'react-native';
import { DraggableBottomSheet } from '@/components/common/draggable-bottom-sheet';
import { PressableScale } from '@/components/common/motion';
import { Screen } from '@/components/common/screen';
import { useToast } from '@/components/common/toast';
import { AppIcon, AppText, BackButton, Card, FormInput, PrimaryButton, ProgressBar, SecondaryButton, StatusChip } from '@/components/common/ui';
import { colors, radii, spacing } from '@/constants/theme';
import { useFinance } from '@/features/finance/FinanceProvider';
import type { SavingsGoal, Wallet, WalletType } from '@/features/finance/types';
import { formatPeso } from '@/lib/format';

const walletTypes: { id: WalletType; label: string; icon: Parameters<typeof AppIcon>[0]['name'] }[] = [
  { id: 'cash', label: 'Cash', icon: 'cash' }, { id: 'gcash', label: 'GCash', icon: 'cellphone' },
  { id: 'maya', label: 'Maya', icon: 'cellphone-check' }, { id: 'bank', label: 'Bank', icon: 'bank-outline' },
  { id: 'other', label: 'Other', icon: 'wallet-outline' },
];
const money = (c: number) => formatPeso(c, { alwaysShowDecimals: true });
const parseMoney = (v: string) => { const n = Number(v.replace(/,/g, '')); return Number.isFinite(n) && n >= 0 ? Math.round(n * 100) : null; };

export function WalletsScreen() {
  const { wallets, loading, error, refresh, saveWallet, archiveWallet } = useFinance();
  const { showToast } = useToast();
  const [editing, setEditing] = useState<Wallet | 'new' | null>(null);
  const [name, setName] = useState(''); const [balance, setBalance] = useState(''); const [type, setType] = useState<WalletType>('cash'); const [isDefault, setDefault] = useState(false); const [saving, setSaving] = useState(false);
  const open = (wallet?: Wallet) => { setEditing(wallet ?? 'new'); setName(wallet?.name ?? ''); setBalance(wallet ? String(wallet.balanceCents / 100) : ''); setType(wallet?.type ?? 'cash'); setDefault(wallet?.isDefault ?? wallets.length === 0); };
  const submit = async () => { const amount = parseMoney(balance); if (!name.trim() || amount === null) { showToast('Enter a wallet name and a valid balance.', { tone: 'warning' }); return; } setSaving(true); const r = await saveWallet({ id: editing !== 'new' && editing ? editing.id : undefined, name, type, balanceCents: amount, isDefault }); setSaving(false); if (!r.ok) return showToast(r.message, { tone: 'warning' }); setEditing(null); showToast('Wallet saved.'); };
  const remove = (wallet: Wallet) => Alert.alert('Archive wallet?', `${wallet.name} will be hidden. Existing expenses keep their history.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { const r = await archiveWallet(wallet.id); showToast(r.ok ? 'Wallet archived.' : r.message, r.ok ? undefined : { tone: 'warning' }); } }]);
  return <Screen bottomInset={40} variant={7} refreshing={loading} onRefresh={refresh}><View style={s.page}><View style={s.header}><BackButton /><View style={s.headerCopy}><AppText variant="title">Wallets</AppText><AppText style={s.muted}>Choose where your expenses come from.</AppText></View></View><Card style={s.totalCard}><AppText style={s.muted}>Account balance</AppText><AppText variant="hero" adjustsFontSizeToFit numberOfLines={1}>{money(wallets.reduce((n, w) => n + w.balanceCents, 0))}</AppText><AppText variant="small" style={s.muted}>Balances are maintained by you; expenses use wallets as payment-source labels.</AppText></Card>{error && !wallets.length ? <Card><AppText variant="h3">Couldn&apos;t load wallets</AppText><SecondaryButton title="Try Again" onPress={refresh} /></Card> : wallets.map(wallet => <PressableScale key={wallet.id} onPress={() => open(wallet)} style={s.item}><View style={s.icon}><AppIcon name={walletTypes.find(x => x.id === wallet.type)?.icon ?? 'wallet-outline'} /></View><View style={s.grow}><View style={s.titleRow}><AppText variant="h3" numberOfLines={1}>{wallet.name}</AppText>{wallet.isDefault ? <StatusChip>Default</StatusChip> : null}</View><AppText style={s.muted}>{walletTypes.find(x => x.id === wallet.type)?.label}</AppText></View><AppText variant="h3">{money(wallet.balanceCents)}</AppText><AppIcon name="chevron-right" color={colors.muted} /></PressableScale>)}<PrimaryButton title="Add Wallet" icon="plus" onPress={() => open()} /></View><DraggableBottomSheet visible={editing !== null} disabled={saving} onClose={() => setEditing(null)}><AppText variant="h2">{editing === 'new' ? 'Add Wallet' : 'Edit Wallet'}</AppText><FormInput label="Wallet name" value={name} onChangeText={setName} maxLength={60} /><AppText variant="bodyMedium">Wallet type</AppText><View style={s.chips}>{walletTypes.map(x => <PressableScale key={x.id} onPress={() => setType(x.id)} style={[s.chip, type === x.id && s.chipActive]}><AppIcon name={x.icon} size={18} color={type === x.id ? colors.surface : colors.deepForest} /><AppText variant="small" style={type === x.id ? s.white : undefined}>{x.label}</AppText></PressableScale>)}</View><FormInput label="Current balance" icon="currency-php" value={balance} onChangeText={setBalance} keyboardType="decimal-pad" /><PressableScale onPress={() => setDefault(v => !v)} style={s.defaultRow}><AppIcon name={isDefault ? 'checkbox-marked-circle' : 'checkbox-blank-circle-outline'} color={colors.success} /><View><AppText variant="bodyMedium">Default wallet</AppText><AppText variant="small" style={s.muted}>Preselected for new manual expenses</AppText></View></PressableScale><PrimaryButton title="Save Wallet" loading={saving} loadingTitle="Saving..." onPress={submit} />{editing && editing !== 'new' ? <SecondaryButton title="Archive Wallet" onPress={() => { setEditing(null); remove(editing); }} /> : null}</DraggableBottomSheet></Screen>;
}

export function GoalsScreen() {
  const { goals, loading, error, refresh, saveGoal, addToGoal, archiveGoal } = useFinance(); const { showToast } = useToast();
  const [mode, setMode] = useState<'new' | 'edit' | 'add' | null>(null); const [selected, setSelected] = useState<SavingsGoal | null>(null); const [name, setName] = useState(''); const [target, setTarget] = useState(''); const [current, setCurrent] = useState(''); const [date, setDate] = useState(''); const [saving, setSaving] = useState(false);
  const openNew = () => { setSelected(null); setMode('new'); setName(''); setTarget(''); setCurrent(''); setDate(''); };
  const openEdit = (g: SavingsGoal) => { setSelected(g); setMode('edit'); setName(g.name); setTarget(String(g.targetCents / 100)); setDate(g.targetDate ?? ''); };
  const openAdd = (g: SavingsGoal) => { setSelected(g); setMode('add'); setCurrent(''); };
  const save = async () => { Keyboard.dismiss(); setSaving(true); let r; if (mode === 'add' && selected) { const n = parseMoney(current); r = n && n > 0 ? await addToGoal(selected, n) : { ok: false as const, message: 'Enter an amount greater than zero.' }; } else { const t = parseMoney(target); const c = parseMoney(current || '0'); r = name.trim() && t && c !== null ? await saveGoal({ id: mode === 'edit' ? selected?.id : undefined, name, targetCents: t, currentCents: c, targetDate: date || null }) : { ok: false as const, message: 'Enter a name and valid target amount.' }; } setSaving(false); if (!r.ok) return showToast(r.message, { tone: 'warning' }); setMode(null); showToast(mode === 'add' ? 'Money added to goal.' : 'Goal saved.'); };
  const remove = (g: SavingsGoal) => Alert.alert('Archive goal?', `${g.name} will be hidden without affecting expenses.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { const r = await archiveGoal(g.id); showToast(r.ok ? 'Goal archived.' : r.message, r.ok ? undefined : { tone: 'warning' }); } }]);
  const saved = useMemo(() => goals.reduce((n, g) => n + g.currentCents, 0), [goals]);
  return <Screen bottomInset={40} variant={9} refreshing={loading} onRefresh={refresh}><View style={s.page}><View style={s.header}><BackButton /><View style={s.headerCopy}><AppText variant="title">Savings Goals</AppText><AppText style={s.muted}>Turn plans into visible progress.</AppText></View></View><Card style={s.totalCard}><AppText style={s.muted}>Saved across goals</AppText><AppText variant="hero">{money(saved)}</AppText></Card>{error && !goals.length ? <Card><AppText variant="h3">Couldn&apos;t load goals</AppText><SecondaryButton title="Try Again" onPress={refresh} /></Card> : goals.map(g => { const pct = Math.round((g.currentCents / g.targetCents) * 100); return <Card key={g.id} style={s.goal}><View style={s.titleRow}><View style={s.grow}><AppText variant="h3">{g.name}</AppText><AppText style={s.muted}>{money(g.currentCents)} of {money(g.targetCents)}</AppText></View>{pct >= 100 ? <StatusChip>Goal reached</StatusChip> : <AppText variant="h3">{pct}%</AppText>}</View><ProgressBar value={pct} />{g.targetDate ? <AppText variant="small" style={s.muted}>Target date: {g.targetDate}</AppText> : null}<View style={s.actions}><PressableScale onPress={() => openAdd(g)} style={s.smallButton}><AppIcon name="plus" size={18} /><AppText variant="small">Add money</AppText></PressableScale><PressableScale onPress={() => openEdit(g)} style={s.smallButton}><AppIcon name="pencil-outline" size={18} /><AppText variant="small">Edit</AppText></PressableScale><PressableScale accessibilityLabel={`Archive ${g.name}`} onPress={() => remove(g)} style={s.iconButton}><AppIcon name="archive-outline" size={20} color={colors.muted} /></PressableScale></View></Card>; })}<PrimaryButton title="Add Goal" icon="plus" onPress={openNew} /></View><DraggableBottomSheet visible={mode !== null} disabled={saving} onClose={() => setMode(null)}><AppText variant="h2">{mode === 'add' ? `Add to ${selected?.name}` : mode === 'edit' ? 'Edit Goal' : 'Add Goal'}</AppText>{mode === 'add' ? <><View style={s.summary}><AppText style={s.muted}>Currently saved</AppText><AppText variant="h3">{money(selected?.currentCents ?? 0)}</AppText></View><FormInput label="Amount to add" icon="currency-php" value={current} onChangeText={setCurrent} keyboardType="decimal-pad" /></> : <><FormInput label="Goal name" value={name} onChangeText={setName} maxLength={80} /><FormInput label="Target amount" icon="currency-php" value={target} onChangeText={setTarget} keyboardType="decimal-pad" />{mode === 'new' ? <FormInput label="Starting amount" icon="currency-php" value={current} onChangeText={setCurrent} keyboardType="decimal-pad" /> : null}<FormInput label="Target date (optional)" placeholder="YYYY-MM-DD" value={date} onChangeText={setDate} /></>}<PrimaryButton title={mode === 'add' ? 'Add to Goal' : 'Save Goal'} loading={saving} loadingTitle="Saving..." onPress={save} /></DraggableBottomSheet></Screen>;
}

const s = StyleSheet.create({ page: { paddingTop: spacing.md, gap: spacing.lg }, header: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, headerCopy: { flex: 1, gap: 3 }, muted: { color: colors.muted }, totalCard: { gap: 8, padding: spacing.xl }, item: { minHeight: 86, borderRadius: radii.md, padding: 14, backgroundColor: 'rgba(255,253,247,.96)', flexDirection: 'row', alignItems: 'center', gap: 12 }, icon: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1, minWidth: 0, gap: 3 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, minHeight: 40, borderRadius: radii.pill, backgroundColor: colors.pale }, chipActive: { backgroundColor: colors.deepForest }, white: { color: colors.surface }, defaultRow: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 12, borderRadius: radii.md, backgroundColor: colors.pale }, goal: { gap: 14 }, actions: { flexDirection: 'row', gap: 8, alignItems: 'center' }, smallButton: { flex: 1, minHeight: 42, borderRadius: radii.pill, backgroundColor: colors.pale, flexDirection: 'row', gap: 5, alignItems: 'center', justifyContent: 'center' }, iconButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pale }, summary: { flexDirection: 'row', justifyContent: 'space-between' } });
